//
//  LocationsDataService.swift
//  Treasureventure
//
//  Created by Jerish Bovas on 2022-04-20.
//

import Foundation
import MapKit

class LocationsDataService {
    static let locations: [Location] = [
        Location(
            name: "Commerce Court",
            description: "Commerce Court in Toronto",
            address: "199 Bay St, Toronto, ON M5L 1L5",
            coordinates: CLLocationCoordinate2D(latitude: 43.6483965, longitude: -79.3794356),
            item: "Golden Key",
            image: "goldenkey",
            difficulty: .Hard,
            ratings: 5),
        Location(
            name: "Art Gallery",
            description: "Art Gallery in Ontarion",
            address: "317 Dundas St W, Toronto, ON M5T 1G4",
            coordinates: CLLocationCoordinate2D(latitude: 43.6535201, longitude: -79.392573),
            item: "Iphone 11",
            image : "iphone",
            difficulty: .Medium,
            ratings: 4),
        Location(
            name: "Cathedral Church",
            description:"Church but unfortunately not to KHS",
            address: "106 King St E, Toronto, ON M5C 2E9",
            coordinates: CLLocationCoordinate2D(latitude: 43.650330, longitude: -79.373756),
            item: "Iphone 10",
            image : "iphone",
            difficulty: .Easy,
            ratings: 4),
        Location(
            name:"Roy Thomson Hall",
            description:"Non profit charity org",
            address:"60 Simcoe St, Toronto, ON M5J 2H5",
            coordinates: CLLocationCoordinate2D(latitude: 43.646710, longitude: -79.386450),
            item:"Samsung S12",
            image : "samsung",
            difficulty:.Easy,
            ratings: 5),
        Location(
            name:"40 Oak Street",
            description:"40 Oak Street",
            address:"40 Oak Street, Toronto, ON M5A 2C6",
            coordinates: CLLocationCoordinate2D(latitude: 43.661221, longitude: -79.365189),
            item:"Takeya Bottle",
            image : "takeyaBottle",
            difficulty:.Hard,
            ratings: 5),
        Location(
            name:"Fatima House",
            description: "Fatima's house",
            address:"1059 College St, Toronto, ON, M6H 1B1",
            coordinates: CLLocationCoordinate2D(latitude: 43.652705, longitude: -79.430278),
            item:"Mac Book",
            image : "macBook",
            difficulty:.Easy,
            ratings: 5),
        Location(
            name:"Bethlehem Shelter",
            description:"Historic shelter",
            address:"1161 Caledonia Rd, North York, ON M6A 2W9",
            coordinates: CLLocationCoordinate2D(latitude: 43.715484619140625, longitude: -79.46754455566406),
            item:"Clock",
            image : "clock",
            difficulty:.Hard,
            ratings: 5),
        Location(
            name:"Women's Bakery",
            description:"Program for women to be empowered",
            address:"145 Front St. East, Toronto, ON, M5A 1E3",
            coordinates: CLLocationCoordinate2D(latitude: 43.6499288, longitude: -79.369279),
            item:"Airpods",
            image : "airpods",
            difficulty:.Hard,
            ratings: 5),
        Location(
            name:"Edward Village",
            description:"Landmark hotel",
            address:"Edward Village,185 Yorkland Blvd, North York M2J 4R2",
            coordinates: CLLocationCoordinate2D(latitude: 43.770423, longitude: -79.335051),
            item:"Iphone 13",
            image : "iphone",
            difficulty:.Hard,
            ratings: 5),
        Location(
            name:"GBC - Casa Loma",
            description:"School campus",
            address:"160 Kendal Ave, Toronto, ON M5R 1M3",
            coordinates: CLLocationCoordinate2D(latitude: 43.675858, longitude: -79.41044),
            item:"Canon Printer",
            image : "printer",
            difficulty:.Hard,
            ratings: 5),
        Location(
            name:"GBC - St. James",
            description:"School campus",
            address:"A Building, 200 King St E, Toronto, ON M5A 3W8",
            coordinates: CLLocationCoordinate2D(latitude: 43.651109, longitude: -79.370189),
            item:"Dell Laptop",
            image : "dell",
            difficulty:.Hard,
            ratings: 5),
        Location(
            name:"Fasken",
            description:"One of largest firms in Canada",
            address:"333 Bay Street, Suite 2400, Toronto, ON, M5H 2T6",
            coordinates: CLLocationCoordinate2D(latitude: 43.650272369384766, longitude: -79.38094329833984),
            item:"Logitech Mx Master 3 Mouse",
            image : "mouse",
            difficulty:.Hard,
            ratings: 5),
        Location(
            name:"Research Library",
            description:"Historic library in Toronto",
            address:"130 St George St, Toronto, ON M5S 1A5, Canada",
            coordinates: CLLocationCoordinate2D(latitude: 43.664537, longitude: -79.399173),
            item:"Yellow Soccer Ball",
            image : "soccerBall",
            difficulty:.Easy,
            ratings: 5),
        Location(
            name:"Gooderham Building",
            description:"Histpric office in Toronto",
            address:"Toronto, Ontario M5A 1S1",
            coordinates: CLLocationCoordinate2D(latitude: 43.653626, longitude: -79.372972),
            item:"Samasung s12",
            image : "samsung",
            difficulty:.Easy,
            ratings: 5),
        Location(
            name:"40 Wellington St",
            description:"40 Wellington St",
            address:"49 Wellington St E, Toronto, ON M5E 1C9, Canada",
            coordinates: CLLocationCoordinate2D(latitude: 43.64851379394531, longitude: -79.37437438964844),
            item:"White Cane",
            image : "whiteCane",
            difficulty:.Hard,
            ratings: 5),
        Location(
            name:"Rogers Centre",
            description:"Sports venue in Toronto",
            address:" 1 Blue Jays Way, Toronto, ON M5V 1J1, Canada",
            coordinates: CLLocationCoordinate2D(latitude: 43.642179, longitude: -79.389371),
            item:"Baseball",
            image : "baseBall",
            difficulty:.Easy,
            ratings: 5),
        Location(
            name:"Learning Centre",
            description:"Center for study and student learning",
            address:"341 Yonge St, Toronto, ON M5B 1S1, Canada",
            coordinates: CLLocationCoordinate2D(latitude: 43.6578096, longitude: -79.3811699),
            item:"White Keyboard",
            image : "keyboard",
            difficulty:.Easy,
            ratings: 5),
        Location(
            name:"Aga Khan Museum",
            description:"Musem of ancient Aga Khan with many artifacts",
            address:"77 Wynford Dr, North York, ON M3C 1K1, Canada",
            coordinates: CLLocationCoordinate2D(latitude: 43.724516, longitude: -79.333776),
            item:"A frammed white T-shirt",
            image : "t-shirt",
            difficulty:.Easy,
            ratings: 5),
        Location(
            name:"Casa Loma",
            description:"An old castle turned into a museum",
            address:"1 Austin Terrace, Toronto, ON M5R 1X8",
            coordinates: CLLocationCoordinate2D(latitude: 43.678122, longitude: -79.409527),
            item:"Holy Bible of KHS with inscription 'All Hail KHS'",
            image : "bible",
            difficulty:.Hard,
            ratings: 5),
        Location(
            name:"Union Station",
            description:"The train station",
            address:"Front Street West, Toronto, Ontario",
            coordinates: CLLocationCoordinate2D(latitude: 43.6426764, longitude: -79.3941238),
            item:"Clock Tower",
            image : "clockTower",
            difficulty:.Easy,
            ratings: 5),
    ]
}
